{
  perSystem = {pkgs, ...}: {
    # `actual` (bin names `actual`/`actual-cli`, from @actual-app/cli's own
    # package.json `bin` field) for Hermes' Actual Budget integration
    # (docs/adr/0012 credential inventory; modules/nixos/hermes/default.nix
    # `extraPackages`). No nixpkgs package exists for this -- verified by
    # evaluating the pinned nixpkgs input directly
    # (`nix eval .#nixosConfigurations.legion-node3.pkgs --apply` filtering
    # attribute names containing "actual" returns only `actual-server`,
    # the sync-server this fleet already runs
    # (modules/nixos/actual-budget.nix), not a CLI) -- and by listing
    # `pkgs/by-name/ac` at the pinned rev 89570f24e97e614aa34aa9ab1c927b6578a43775
    # via `gh api repos/NixOS/nixpkgs/contents/pkgs/by-name/ac`, same result.
    # It ships only on npm, as `@actual-app/cli`
    # (verified: `https://registry.npmjs.org/@actual-app/cli`, latest
    # 26.8.0, repository github.com/actualbudget/actual, directory
    # `packages/cli`) -- the exact package behind the commands documented
    # in ~/.claude/skills/actual-budget-import/references/actual-cli.md
    # (confirmed by building this derivation and running `actual --help`:
    # the same `--server-url`/`--password`/`--session-token`/`--sync-id`
    # flags and env vars, and `accounts`/`transactions` subcommands).
    #
    # `@actual-app/cli` lives in a yarn-workspace monorepo
    # (actualbudget/actual) and depends on `@actual-app/api` via
    # `"workspace:*"` -- unresolvable outside that monorepo, and building
    # the monorepo from source would mean vendoring its own toolchain
    # (lage/vite) for no benefit, since npm's published tarball already
    # ships the built `dist/cli.js`. `./actual-cli/package.json` is
    # instead a synthetic single-dependency project
    # (`"@actual-app/cli": "26.8.0"`, `bin` pointing at the installed
    # package's own `dist/cli.js`) with a `package-lock.json` generated by
    # `npm install --package-lock-only` against the real registry -- for
    # an external (non-workspace) install, npm resolves `workspace:*` to
    # the matching published `@actual-app/api@26.8.0`, so this lockfile is
    # an ordinary, buildable dependency graph. `buildNpmPackage`'s
    # `npmDepsHash` below fetches and verifies every tarball it names as
    # one fixed-output derivation -- network only inside that FOD's own
    # sandbox, exactly the same mechanism this repo already uses for other
    # pinned-ahead-of-nixpkgs sources (e.g. `modules/packages/netbird.nix`'s
    # `fetchFromGitHub` `hash`), nothing at eval time or in the main build.
    #
    # One dependency, `better-sqlite3`, has a native install script
    # (`prebuild-install || node-gyp rebuild --release`). This builds fully
    # offline: `buildNpmPackage`'s own `npmConfigHook` runs
    # `npm ci --ignore-scripts` from the pre-fetched FOD cache (still no
    # network), then a separate `npm rebuild` WITHOUT `--ignore-scripts`
    # with `npm_config_nodedir`/`npm_config_node_gyp` pointed at the
    # Nix-store Node headers/toolchain (verified against
    # pkgs/build-support/node/build-npm-package/hooks/npm-config-hook.sh at
    # the pinned rev) -- `prebuild-install`'s network attempt fails with no
    # network in the build sandbox, and its own `||` falls through to
    # `node-gyp rebuild --release` against those local headers, which
    # succeeds. Confirmed by an actual offline build producing
    # `better_sqlite3.node` with no build failures (aarch64-darwin, this
    # nixpkgs input; the target platform is x86_64-linux, but nothing in
    # this derivation is platform-conditional).
    packages.actual-cli = pkgs.buildNpmPackage {
      pname = "actual-cli";
      version = "26.8.0";
      src = ./actual-cli;
      npmDepsHash = "sha256-P/vhWRC7seajfSWrZNHDtiizuAMlQ8LWOudclFwKpS0=";
      # The synthetic root package.json declares no build script (the
      # installed @actual-app/cli tarball already ships its built
      # dist/cli.js).
      dontNpmBuild = true;
      meta = {
        description = "Actual Budget CLI (@actual-app/cli), packaged standalone from the npm registry for Hermes";
        mainProgram = "actual";
      };
    };
  };
}
