keys:
  - &server_solder age1vsvztaxkcqduvyawf6ak5rv3f63ujq6ucm5855ernuh7tj8uhahsxqx9ar
  - &user_aidanp age1yy2uxasknys578edlnepcxug2j37ntep0tudfv9nr7qqx6d9ws3sack68y
  - &server_artemis age1fm8meecmpus97y9ra9gjdk08g8njran6fv4jxnr0zegpfd89a9esayj39c
  - &server_legion_node1 age1fexn9r8huh294w3hmyst605fndjagyg7e3s23aqfedlqrqnn24rq5lvgr7
  - &server_legion_node2 age1f9t7ktuy3hny3lju3692mqx35mrc0wrfrl8mtelyeecc4lydcu0snxtm23
  - &server_legion_node3 age1yc37qpvazdtfswa38057e73sh523q0exj75qqahzgax6kqaxeqmsq2wx9t
  - &server_legion_node4 age1a80m5fpv387njdmg63q6vvkavahepdkx7zq4gjjkg62x3lme4f7q9s5c66

creation_rules:
  - path_regex: secrets(\.[^.]+)?\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *server_solder
      - *server_artemis
      - *user_aidanp
      - *server_legion_node1
      - *server_legion_node2
      - *server_legion_node3
      - *server_legion_node4
