keys:
  - &solder-system age19n36a0l20fv374dmld7zknxv825q3wmes399q4r47deuggewwqgsw37m9k
  - &aidanp-gpg A23C4EC9045EB889D82D17A4D980BA361E9FA4E3
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - pgp:
          - *aidanp-gpg
        age:
          - *solder-system
