keys:
  - &server_solder age1vsvztaxkcqduvyawf6ak5rv3f63ujq6ucm5855ernuh7tj8uhahsxqx9ar
  - &user_aidanp age1yy2uxasknys578edlnepcxug2j37ntep0tudfv9nr7qqx6d9ws3sack68y

creation_rules:
  - path_regex: secrets\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *server_solder
      - *user_aidanp
