keys:
  - &solder-system age1z27dx9q09dul0nsm9e5quazz4ja55tjx806nnwa4raqdtfy9upwsqwh698
  - &aidanp-gpg A23C4EC9045EB889D82D17A4D980BA361E9FA4E3
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - pgp:
          - *aidanp-gpg
        age:
          - *solder-system
