# nvfetcher.toml
[manix]
src.git = "https://github.com/mlvzk/manix"
fetch.github = "mlvzk/manix"

[wezterm]
src.git = "https://github.com/wez/wezterm"
fetch.github = "wez/wezterm"
cargo_locks = [ "./Cargo.lock" ]
git.fetchSubmodules = true

[joshuto]
src.git = "https://github.com/kamiyaa/joshuto"
fetch.github = "kamiyaa/joshuto"
cargo_locks = [ "./Cargo.lock" ]
