# nvfetcher.toml
[manix]
src.git = "https://github.com/mlvzk/manix"
fetch.github = "mlvzk/manix"

[wezterm]
src.git = "https://github.com/wez/wezterm"
fetch.github = "wez/wezterm"
git.fetchSubmodules = true
