# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchFromGitHub,
}: {
  wezterm = {
    pname = "wezterm";
    version = "d6809533215e273ca23e52614c886929ad702715";
    src = fetchFromGitHub {
      owner = "wez";
      repo = "wezterm";
      rev = "d6809533215e273ca23e52614c886929ad702715";
      fetchSubmodules = true;
      sha256 = "sha256-ZnmBKBiaqKGKKrItTrPf/LGJvtu7BBvu1+QAk5PBi6g=";
    };
    cargoLock."./Cargo.lock" = {
      lockFile = ./wezterm-d6809533215e273ca23e52614c886929ad702715/./Cargo.lock;
      outputHashes = {
        "xcb-1.2.1" = "sha256-zkuW5ATix3WXBAj2hzum1MJ5JTX3+uVQ01R1vL6F1rY=";
        "xcb-imdkit-0.2.0" = "sha256-L+NKD0rsCk9bFABQF4FZi9YoqBHr4VAZeKAWgsaAegw=";
      };
    };
    date = "2023-11-04";
  };
}
