[[language]]
name = "nix"
formatter = { command = "treefmt", args = [ "--stdin", "--quiet", "%{buffer_name}" ] }
auto-format = true

[[language]]
name = "lua"
indent = { tab-width = 2, unit = "\t" }
formatter = { command = "treefmt", args = [ "--stdin", "--quiet", "%{buffer_name}" ] }
auto-format = true
