{self, ...}: {
  # docs/MIGRATION.md piece 3.1: NetBird management/signal server + relay
  # for legion-node2. Custom local module (DESIGN.md Service Ownership):
  # nixpkgs has no unified-server first-party module, and its split
  # netbird-mgmt uses a materially different state layout than the deployed
  # combined server (modules/packages/netbird-server.nix). Imported only
  # for the inventory node that places `netbird-server`
  # (modules/hosts/legion/default.nix), the same optional-import pattern as
  # self.nixosModules.edge. Never imported on artemis or any other node.
  flake.nixosModules.netbird-server = {
    config,
    lib,
    pkgs,
    ...
  }: let
    system = pkgs.stdenv.hostPlatform.system;
    serverPkg = self.packages.${system}.netbird-server;
    relayPkg = self.packages.${system}.netbird-relay;

    # legion-node2's declared Volume mountpoint
    # (modules/hosts/legion/_service-inventory.nix netbird-server.volume).
    # The Volume itself is an external prerequisite (DESIGN.md: Volumes are
    # provisioned outside this flake); mounting it here and copying the
    # existing k8s PVC content in is docs/runbooks/netbird-migration.md
    # (piece 3.3), not this module.
    dataDir = "/mnt/netbird";

    # Matches modules/nixos/edge/default.nix's @relay backend port
    # (`reverse_proxy ${node2}:8080`) and the
    # `netbird-relay` firewall entry in
    # modules/hosts/legion/_service-inventory.nix.
    relayPort = 8080;
    stunPort = 3478;
    metricsPort = 9091;

    # Rendered to match the deployed chart's shape exactly
    # (k8s-manifests netbird/templates/server.yaml's render-config
    # initContainer + netbird/values.yaml), except `dataDir` (Volume
    # mountpoint here instead of the chart's /var/lib/netbird -- see
    # above) and the secret values (sops placeholders here instead of the
    # chart's shell-expanded env vars).
    configYaml = ''
      server:
        listenAddress: ":80"
        exposedAddress: "https://netbird.jeiang.dev:443"
        metricsPort: 9090
        healthcheckAddress: ":9000"
        logLevel: "info"
        logFile: "console"
        tls:
          certFile: ""
          keyFile: ""
          letsencrypt:
            enabled: false
            dataDir: ""
            domains: []
            email: ""
            awsRoute53: false
        authSecret: "${config.sops.placeholder."netbird/relay-auth-secret"}"
        dataDir: "${dataDir}"
        stuns:
          - uri: "stun:stun.netbird.jeiang.dev:${toString stunPort}"
            proto: "udp"
        relays:
          addresses:
            - "rels://netbird.jeiang.dev:443"
          secret: "${config.sops.placeholder."netbird/relay-auth-secret"}"
          credentialsTTL: "24h"
        disableAnonymousMetrics: false
        disableGeoliteUpdate: false
        auth:
          # NetBird's own built-in local auth, matching the deployed chart
          # exactly: k8s-manifests netbird/templates/server.yaml renders
          # `issuer` as the server's own /oauth2 endpoint, and
          # netbird/values.yaml has no `idp:`-style block anywhere. The
          # Pocket ID OIDC client documented in k8s-manifests
          # idp/README.md ("Create NetBird OIDC Client") is available for
          # optional future use but the live server config never reads a
          # Pocket ID client ID/secret -- there is nothing to carry over
          # here.
          issuer: "https://netbird.jeiang.dev/oauth2"
          localAuthDisabled: false
          signKeyRefreshEnabled: true
          sessionCookieEncryptionKey: "${config.sops.placeholder."netbird/idp-session-cookie-encryption-key"}"
          dashboardRedirectURIs:
            - "https://netbird.jeiang.dev/nb-auth"
            - "https://netbird.jeiang.dev/nb-silent-auth"
          cliRedirectURIs:
            - "http://localhost:53000/"
        dnsDomain: "jeiang.vpn"
        store:
          engine: "sqlite"
          dsn: ""
          encryptionKey: "${config.sops.placeholder."netbird/store-encryption-key"}"
    '';
  in {
    # Same set the chart's README lists, minus the reverse-proxy token
    # (piece 3.2's concern -- the server config above never reads it; it's
    # generated by `netbird-server token create` after this service is
    # running) and the CrowdSec bouncer key (piece 3.2's proxy bouncer,
    # not consumed here). Operator fills these via `just sops-edit` before
    # first deploy (sops-nix only checks at activation time, not eval
    # time, so it's safe to land the module first -- same as the edge
    # module's hetzner-dns-token).
    sops = {
      secrets = {
        "netbird/store-encryption-key" = {};
        "netbird/relay-auth-secret" = {};
        "netbird/idp-session-cookie-encryption-key" = {};
      };

      templates = {
        "netbird-server-config.yaml" = {
          owner = "netbird";
          group = "netbird";
          content = configYaml;
        };

        "netbird-relay.env".content = "NB_AUTH_SECRET=${config.sops.placeholder."netbird/relay-auth-secret"}\n";
      };
    };

    users.groups.netbird = {};
    users.users.netbird = {
      isSystemUser = true;
      group = "netbird";
    };

    systemd = {
      # The Volume mount itself is an external prerequisite (see `dataDir`
      # above); this only fixes ownership/mode once it exists, so the
      # runbook can copy PVC content in as root and hand it to the service
      # user.
      tmpfiles.rules = ["d ${dataDir} 0750 netbird netbird - -"];

      services = {
        netbird-server = {
          description = "NetBird unified management/signal server";
          after = ["network-online.target"];
          wants = ["network-online.target"];
          wantedBy = ["multi-user.target"];
          # Mount guard (Codex review C2): refuse to start unless
          # ${dataDir} is actually mounted, so a missing/late Volume never
          # silently initializes a fresh sqlite store.engine on the root
          # disk instead of the retained data.
          unitConfig = {
            RequiresMountsFor = [dataDir];
            ConditionPathIsMountPoint = dataDir;
          };
          serviceConfig = {
            ExecStart = "${lib.getExe serverPkg} --config ${config.sops.templates."netbird-server-config.yaml".path}";
            Restart = "on-failure";
            RestartSec = 5;
            User = "netbird";
            Group = "netbird";
            # listenAddress above binds :80; the server otherwise runs
            # unprivileged.
            AmbientCapabilities = ["CAP_NET_BIND_SERVICE"];
            # piece 0.6 capacity audit, docs/MIGRATION.md.
            MemoryMax = "320M";
          };
        };

        netbird-relay = {
          description = "NetBird relay + STUN server";
          after = ["network-online.target"];
          wants = ["network-online.target"];
          wantedBy = ["multi-user.target"];
          environment = {
            NB_LISTEN_ADDRESS = ":${toString relayPort}";
            # Public address advertised to peers (matches
            # k8s-manifests netbird/values.yaml relay.exposedAddress):
            # reached through the edge's netbird.jeiang.dev:443 @relay
            # route, not this node's own relayPort directly.
            NB_EXPOSED_ADDRESS = "rels://netbird.jeiang.dev:443";
            NB_ENABLE_STUN = "true";
            NB_STUN_PORTS = toString stunPort;
            NB_LOG_LEVEL = "info";
            NB_METRICS_PORT = toString metricsPort;
          };
          serviceConfig = {
            ExecStart = lib.getExe relayPkg;
            EnvironmentFile = [config.sops.templates."netbird-relay.env".path];
            Restart = "on-failure";
            RestartSec = 5;
            DynamicUser = true;
            # piece 0.6 capacity audit, docs/MIGRATION.md.
            MemoryMax = "96M";
          };
        };
      };
    };
  };
}
