{self, ...}: {
  # NetBird management/signal server + relay for legion-node2. Custom
  # local module (DESIGN.md Service Ownership): nixpkgs has no
  # unified-server first-party module, and its split netbird-mgmt uses a
  # materially different state layout than the combined server
  # (modules/packages/netbird-server.nix). Imported only for the
  # inventory node that places `netbird-server`
  # (modules/hosts/legion/default.nix), the same optional-import pattern as
  # self.nixosModules.edge. Never imported on artemis or any other node.
  flake.nixosModules.netbird-server = {
    config,
    lib,
    pkgs,
    ...
  }: let
    system = pkgs.stdenv.hostPlatform.system;
    serverPkg = self.packages.${system}.netbird-server;
    relayPkg = self.packages.${system}.netbird-relay;

    # legion-node2's declared Volume mountpoint
    # (modules/hosts/legion/_service-inventory.nix netbird-server.volume).
    # The Volume itself is an external prerequisite (DESIGN.md: Volumes are
    # provisioned outside this flake); populating it is not this module's
    # concern.
    dataDir = "/mnt/netbird";

    sopsFile = ./secrets.yaml;

    # Matches modules/nixos/edge/default.nix's @relay backend port
    # (`reverse_proxy ${node2}:8080`) and the
    # `netbird-relay` firewall entry in
    # modules/hosts/legion/_service-inventory.nix.
    relayPort = 8080;
    stunPort = 3478;
    metricsPort = 9091;
    healthcheckPort = 9001;

    # Renders NetBird's config.yaml schema (see
    # modules/packages/netbird-server.nix's `combined/config.yaml.example`
    # reference), with `dataDir` pointed at the Volume mountpoint above
    # and secret values filled in via sops placeholders.
    configYaml = ''
      server:
        listenAddress: ":80"
        exposedAddress: "https://netbird.jeiang.dev:443"
        metricsPort: 9090
        healthcheckAddress: ":9000"
        logLevel: "info"
        logFile: "console"
        tls:
          certFile: ""
          keyFile: ""
          letsencrypt:
            enabled: false
            dataDir: ""
            domains: []
            email: ""
            awsRoute53: false
        authSecret: "${config.sops.placeholder."netbird/relay-auth-secret"}"
        dataDir: "${dataDir}"
        stuns:
          - uri: "stun:stun.netbird.jeiang.dev:${toString stunPort}"
            proto: "udp"
        relays:
          addresses:
            - "rels://netbird.jeiang.dev:443"
          secret: "${config.sops.placeholder."netbird/relay-auth-secret"}"
          credentialsTTL: "24h"
        disableAnonymousMetrics: false
        disableGeoliteUpdate: false
        auth:
          # NetBird's own built-in local auth: `issuer` is the server's
          # own /oauth2 endpoint. A Pocket ID OIDC client is available for
          # optional future use but the live server config never reads a
          # Pocket ID client ID/secret -- there is nothing to carry over
          # here.
          issuer: "https://netbird.jeiang.dev/oauth2"
          localAuthDisabled: false
          signKeyRefreshEnabled: true
          sessionCookieEncryptionKey: "${config.sops.placeholder."netbird/idp-session-cookie-encryption-key"}"
          dashboardRedirectURIs:
            - "https://netbird.jeiang.dev/nb-auth"
            - "https://netbird.jeiang.dev/nb-silent-auth"
          cliRedirectURIs:
            - "http://localhost:53000/"
        dnsDomain: "jeiang.vpn"
        store:
          engine: "sqlite"
          dsn: ""
          encryptionKey: "${config.sops.placeholder."netbird/store-encryption-key"}"
    '';
  in {
    # These three secrets, minus the reverse-proxy token (the server
    # config above never reads it; it's generated by `netbird-server token
    # create` after this service is running) and the CrowdSec bouncer key
    # for the proxy bouncer (not consumed here).
    sops = {
      secrets = {
        "netbird/store-encryption-key" = {inherit sopsFile;};
        "netbird/relay-auth-secret" = {inherit sopsFile;};
        "netbird/idp-session-cookie-encryption-key" = {inherit sopsFile;};
      };

      # restartUnits on both: the config file is read once at start-up
      # (--config) and the EnvironmentFile once by systemd, while a deploy
      # that only rotates a secret leaves both unit definitions
      # byte-identical -- so without this the running processes keep the
      # pre-rotation values, and the relay's NB_AUTH_SECRET would silently
      # disagree with the server's `relays.secret`. See
      # modules/nixos/garret/default.nix for the observed failure.
      templates = {
        "netbird-server-config.yaml" = {
          owner = "netbird";
          group = "netbird";
          restartUnits = ["netbird-server.service"];
          content = configYaml;
        };

        "netbird-relay.env" = {
          restartUnits = ["netbird-relay.service"];
          content = "NB_AUTH_SECRET=${config.sops.placeholder."netbird/relay-auth-secret"}\n";
        };
      };
    };

    users.groups.netbird = {};
    users.users.netbird = {
      isSystemUser = true;
      group = "netbird";
    };

    systemd = {
      services = {
        # Mount guard (flake.lib.mountGuard, modules/hosts/legion/default.nix)
        # merged in via `//`: refuse to start unless ${dataDir} is
        # actually mounted, so a missing/late Volume never silently
        # initializes a fresh sqlite store.engine on the root disk
        # instead of the retained data.
        netbird-server =
          {
            description = "NetBird unified management/signal server";
            after = ["network-online.target"];
            wants = ["network-online.target"];
            wantedBy = ["multi-user.target"];
            serviceConfig = {
              ExecStart = "${lib.getExe serverPkg} --config ${config.sops.templates."netbird-server-config.yaml".path}";
              # Ownership of the Volume root (external prerequisite, see
              # `dataDir` above), so the runbook can copy PVC content in as
              # root and hand it to the service user. An ExecStartPre, NOT
              # `systemd.tmpfiles.rules`: systemd-tmpfiles-setup.service is
              # not ordered after this Volume's mount unit, so on the
              # activation that first mounts the Volume a tmpfiles rule
              # runs against the empty pre-mount directory and the mount
              # then hides its work. This inherits the unit's own
              # `RequiresMountsFor` (mountGuard below), so it cannot run
              # before the mount exists. Same reasoning and same shape as
              # modules/nixos/garret/default.nix's `ensureDataDir`; `+`
              # runs it as root despite User=netbird.
              ExecStartPre = "+${pkgs.coreutils}/bin/install -d -o netbird -g netbird -m 0750 ${dataDir}";
              Restart = "on-failure";
              RestartSec = 5;
              User = "netbird";
              Group = "netbird";
              # listenAddress above binds :80; the server otherwise runs
              # unprivileged.
              AmbientCapabilities = ["CAP_NET_BIND_SERVICE"];
              MemoryMax = "320M";
            };
          }
          // self.lib.mountGuard dataDir;

        netbird-relay = {
          description = "NetBird relay + STUN server";
          after = ["network-online.target"];
          wants = ["network-online.target"];
          wantedBy = ["multi-user.target"];
          environment = {
            NB_LISTEN_ADDRESS = ":${toString relayPort}";
            # Public address advertised to peers: reached through the
            # edge's netbird.jeiang.dev:443 @relay route, not this node's
            # own relayPort directly.
            NB_EXPOSED_ADDRESS = "rels://netbird.jeiang.dev:443";
            NB_ENABLE_STUN = "true";
            NB_STUN_PORTS = toString stunPort;
            NB_LOG_LEVEL = "info";
            NB_METRICS_PORT = toString metricsPort;
            NB_HEALTH_LISTEN_ADDRESS = ":${toString healthcheckPort}";
          };
          serviceConfig = {
            ExecStart = lib.getExe relayPkg;
            EnvironmentFile = [config.sops.templates."netbird-relay.env".path];
            Restart = "on-failure";
            RestartSec = 5;
            DynamicUser = true;
            MemoryMax = "96M";
          };
        };
      };
    };
  };
}
