{self, ...}: {
  flake.nixosModules.netbird-proxy = {
    config,
    lib,
    pkgs,
    ...
  }: let
    system = pkgs.stdenv.hostPlatform.system;
    proxyPkg = self.packages.${system}.netbird-proxy;

    domain = "proxy.jeiang.dev";
    certName = domain;

    netbirdProxySopsFile = ./secrets.proxy.yaml;
    crowdsecSopsFile = ../crowdsec/secrets.yaml;

    node1PrivateIp = self.lib.legionNodes.legion-node1.privateIPv4;
    lapiPort = 8080;

    # Static-cert mode: security.acme provisions the DNS-01 wildcard and the
    # proxy's own file watcher picks up renewals, so no reloadServices hook
    # is wired and the built-in ACME path is unused.
    acmeCertDir = config.security.acme.certs.${certName}.directory;
  in {
    security.acme = {
      acceptTerms = true;
      defaults.email = "aidan@aidanpinard.co";

      certs.${certName} = {
        extraDomainNames = ["*.${domain}"];
        dnsProvider = "cloudflare";
        environmentFile = config.sops.templates."netbird-proxy-cloudflare-dns.env".path;
        group = "netbird-proxy";
      };
    };

    sops = {
      secrets = {
        # Generated by `netbird-server token create` against the local
        # management server.
        "netbird/proxy-token" = {sopsFile = netbirdProxySopsFile;};
        # Same key modules/nixos/crowdsec/default.nix registers at node1's
        # LAPI; node2 needs `just sops-updatekeys` once the value exists.
        "crowdsec/bouncer-netbird-proxy-key" = {sopsFile = crowdsecSopsFile;};
        # Same Cloudflare DNS API token value as the edge's
        # caddy/cloudflare-dns-token, declared per host.
        "netbird-proxy/cloudflare-dns-token" = {sopsFile = netbirdProxySopsFile;};
        # Registered at node1's LAPI as "legion-node2-firewall" by
        # modules/nixos/crowdsec/default.nix.
        "crowdsec/bouncer-legion-node2-firewall" = {
          sopsFile = crowdsecSopsFile;
          restartUnits = ["crowdsec-firewall-bouncer.service"];
        };
      };

      templates = {
        "netbird-proxy.env" = {
          owner = "netbird-proxy";
          restartUnits = ["netbird-proxy.service"];
          content = ''
            NB_PROXY_TOKEN=${config.sops.placeholder."netbird/proxy-token"}
            NB_PROXY_CROWDSEC_API_KEY=${config.sops.placeholder."crowdsec/bouncer-netbird-proxy-key"}
          '';
        };

        "netbird-proxy-cloudflare-dns.env".content = ''
          CF_DNS_API_TOKEN=${config.sops.placeholder."netbird-proxy/cloudflare-dns-token"}
        '';
      };
    };

    users.groups.netbird-proxy = {};
    users.users.netbird-proxy = {
      isSystemUser = true;
      group = "netbird-proxy";
    };

    systemd.services.netbird-proxy = {
      description = "NetBird reverse proxy";
      # Wants, not Requires, on both: the proxy must not go down when the
      # server restarts; the acme ordering is first-issuance only and
      # renewals never restart this unit.
      after = [
        "network-online.target"
        "netbird-server.service"
        "acme-${certName}.service"
      ];
      wants = [
        "network-online.target"
        "netbird-server.service"
        "acme-${certName}.service"
      ];
      wantedBy = ["multi-user.target"];
      environment = {
        NB_PROXY_ADDRESS = ":443";
        NB_PROXY_DOMAIN = domain;
        # The default localhost:8080 collides with the relay's WS port on
        # this node; 9002 continues the netbird health band (9000, 9001).
        NB_PROXY_HEALTH_ADDRESS = "localhost:9002";
        # The management connection MUST be TLS (gRPC refuses per-RPC
        # credentials over plaintext) and the local server is plain :80, so
        # this hairpins through the edge's TLS-terminating @grpc route.
        NB_PROXY_MANAGEMENT_ADDRESS = "https://netbird.jeiang.dev";
        NB_PROXY_CERTIFICATE_DIRECTORY = acmeCertDir;
        NB_PROXY_CERTIFICATE_FILE = "fullchain.pem";
        NB_PROXY_CERTIFICATE_KEY_FILE = "key.pem";
        # NB_PROXY_PROXY_PROTOCOL/NB_PROXY_TRUSTED_PROXIES must stay unset:
        # no upstream sends the header, and expecting one would break every
        # direct connection on this public node.
        NB_PROXY_ACME_CERTIFICATES = "false";
        # Enforcement is per-service in the NetBird dashboard; `observe`
        # (or unset) always fails open, only `enforce` fails closed on an
        # unreachable LAPI -- start new services in observe.
        NB_PROXY_CROWDSEC_API_URL = "http://${node1PrivateIp}:${toString lapiPort}";
        NB_PROXY_LOG_LEVEL = "info";
      };
      serviceConfig = {
        ExecStart = lib.getExe proxyPkg;
        EnvironmentFile = [config.sops.templates."netbird-proxy.env".path];
        Restart = "on-failure";
        RestartSec = 5;
        User = "netbird-proxy";
        Group = "netbird-proxy";
        AmbientCapabilities = ["CAP_NET_BIND_SERVICE"];
        MemoryMax = "128M";
      };
    };

    # Whole-node nftables remediation, alongside the per-service app-level
    # bouncer above; both talk to node1's LAPI over the private network.
    services.crowdsec-firewall-bouncer = {
      enable = true;
      settings = {
        mode = "nftables";
        api_url = "http://${node1PrivateIp}:${toString lapiPort}";
      };
      # Not registerBouncer.enable: that registers against a local crowdsec
      # service this node doesn't run; registration lives on node1.
      secrets.apiKeyPath = config.sops.secrets."crowdsec/bouncer-legion-node2-firewall".path;
    };
  };
}
