{self, ...}: {
  # NetBird reverse proxy (`netbird-proxy`) for legion-node2, receiving
  # the edge's raw SNI passthrough for proxy.jeiang.dev/*.proxy.jeiang.dev
  # (modules/nixos/edge/default.nix). Sibling file to
  # modules/nixos/netbird-server/default.nix: same node, same service
  # boundary, imported under the same optional pattern
  # (modules/hosts/legion/default.nix, gated on the inventory placing
  # `netbird-proxy` -- modules/hosts/legion/_service-inventory.nix).
  flake.nixosModules.netbird-proxy = {
    config,
    lib,
    pkgs,
    ...
  }: let
    system = pkgs.stdenv.hostPlatform.system;
    proxyPkg = self.packages.${system}.netbird-proxy;

    domain = "proxy.jeiang.dev";
    certName = domain;

    # legion-node1's private address (modules/hosts/legion/default.nix
    # legionNodes.legion-node1.privateIPv4) and CrowdSec's LAPI port
    # (modules/nixos/crowdsec/default.nix lapiPort) -- the edge bouncer
    # never sees this passthrough traffic, so the proxy runs its own
    # bouncer against the same LAPI over the private network.
    node1PrivateIp = "172.17.0.1";
    lapiPort = 8080;

    # TLS strategy: the nixpkgs-pinned netbird-proxy binary (v0.74.3,
    # `nix build .#netbird-proxy && netbird-proxy --help`) exposes
    # `--cert-dir`/`--cert-file`/`--cert-key-file`, consumed by
    # `configureTLS` in proxy/server.go as a plain static-certificate path
    # with its own file watcher (certwatch) whenever `--acme-certs` is
    # false (the default) -- confirmed against the v0.74.3 source
    # (github.com/netbirdio/netbird proxy/server.go `configureTLS`,
    # proxy/cmd/proxy/cmd/root.go flag wiring). So the proxy does NOT need
    # its own ACME at all: `security.acme` below provisions a DNS-01
    # wildcard for proxy.jeiang.dev/*.proxy.jeiang.dev via the Hetzner
    # provider (same mechanism as the edge's *.jeiang.dev cert,
    # modules/nixos/edge/default.nix) and hands the rendered
    # fullchain.pem/key.pem straight to the proxy; the built-in ACME
    # (TLS-ALPN-01) path is unused. The proxy's file watcher picks up
    # renewals without a restart, so no reload hook is wired
    # (`security.acme.certs.${certName}.reloadServices` deliberately left
    # unset -- see the systemd block below for the first-issuance
    # ordering that IS needed).
    acmeCertDir = config.security.acme.certs.${certName}.directory;
  in {
    security.acme = {
      acceptTerms = true;
      # Same operator identity that owns the other Hetzner-DNS domains this
      # flake issues certs for (aidanpinard.co, via Caddy's ACME on the
      # edge); Let's Encrypt requires a contact address for the account.
      defaults.email = "aidan@aidanpinard.co";

      certs.${certName} = {
        extraDomainNames = ["*.${domain}"];
        dnsProvider = "hetzner";
        environmentFile = config.sops.templates."netbird-proxy-hetzner-dns.env".path;
        # /var/lib/acme/${certName} readable by this group (chmod
        # u=rwX,g=rX,o= in the nixos acme module); netbird-proxy's service
        # user is added to it below instead of the module default "acme".
        group = "netbird-proxy";
      };
    };

    # State decision: unlike netbird-server's /mnt/netbird, this module
    # mounts nothing on the /mnt/netbird-proxy Volume the inventory
    # declares (modules/hosts/legion/_service-inventory.nix) -- that entry
    # exists for a built-in-ACME fallback this module doesn't use. Static
    # externally-provisioned certs (above) mean the proxy itself keeps
    # zero required persistent state: its ACME material lives in
    # security.acme's own node-local /var/lib/acme/${certName}, reissued
    # via DNS-01 on every reinstall -- wildcard DNS-01 has generous Let's
    # Encrypt rate limits, so losing that state costs a few seconds of
    # reissuance, not a rate-limit incident.
    sops = {
      secrets = {
        # NetBird reverse-proxy access token (`nbx_...`), generated by
        # `netbird-server token create` against the local management
        # server. Declared here even though the value doesn't exist in
        # secrets.yaml yet -- sops-nix only checks at activation time,
        # same precedent as modules/nixos/netbird-server/default.nix's
        # secrets.
        "netbird/proxy-token" = {};
        # Reuses the bouncer key modules/nixos/crowdsec/default.nix
        # registers at node1's LAPI; legion-node2 needs `just
        # sops-updatekeys` run against it once this secret has a real
        # value.
        "crowdsec/bouncer-netbird-proxy-key" = {};
        # Same Hetzner DNS API token value as the edge's
        # `caddy/hetzner-dns-token` (modules/nixos/edge/default.nix),
        # stored under its own name since sops secrets are declared (and
        # keyed to recipients) per host.
        "netbird-proxy/hetzner-dns-token" = {};
      };

      templates = {
        "netbird-proxy.env".owner = "netbird-proxy";
        "netbird-proxy.env".content = ''
          NB_PROXY_TOKEN=${config.sops.placeholder."netbird/proxy-token"}
          NB_PROXY_CROWDSEC_API_KEY=${config.sops.placeholder."crowdsec/bouncer-netbird-proxy-key"}
        '';

        "netbird-proxy-hetzner-dns.env".content = ''
          HETZNER_API_TOKEN=${config.sops.placeholder."netbird-proxy/hetzner-dns-token"}
        '';
      };
    };

    users.groups.netbird-proxy = {};
    users.users.netbird-proxy = {
      isSystemUser = true;
      group = "netbird-proxy";
    };

    systemd.services.netbird-proxy = {
      description = "NetBird reverse proxy";
      after = [
        "network-online.target"
        # Registers against the local management server; Wants, not
        # Requires -- must not go down just because the server restarts.
        "netbird-server.service"
        # First-issuance ordering only: waits for the initial DNS-01 cert
        # to exist before the proxy's static-cert file watcher has
        # anything to watch. Renewals afterwards don't restart this unit
        # (see the `security.acme` comment above) -- Wants, not Requires,
        # so a failed/delayed renewal never takes the proxy down either.
        "acme-${certName}.service"
      ];
      wants = [
        "network-online.target"
        "netbird-server.service"
        "acme-${certName}.service"
      ];
      wantedBy = ["multi-user.target"];
      environment = {
        NB_PROXY_ADDRESS = ":443";
        NB_PROXY_DOMAIN = domain;
        # Loopback on the same node as the server (its config.yaml
        # `server.listenAddress` is plain-HTTP ":80", so http:// here is
        # correct, not a downgrade).
        NB_PROXY_MANAGEMENT_ADDRESS = "http://127.0.0.1:80";
        NB_PROXY_CERTIFICATE_DIRECTORY = acmeCertDir;
        NB_PROXY_CERTIFICATE_FILE = "fullchain.pem";
        NB_PROXY_CERTIFICATE_KEY_FILE = "key.pem";
        # Counterpart to the edge's `proxy_protocol v2` on the l4 proxy
        # handler dialing this node (modules/nixos/edge/default.nix) --
        # BOTH ends must agree or the TLS stream breaks. Verified against
        # the nixpkgs-pinned v0.74.3 source
        # (proxy/cmd/proxy/cmd/root.go flag wiring, proxy/server.go
        # `ProxyProtocol bool` / `wrapProxyProtocol`): the flag is a
        # boolean toggle (auto-detects v1/v2 on read, unlike caddy-l4's
        # explicit `v2`), and TrustedProxies gates which source IPs may
        # send the header at all -- connections from anyone else have it
        # stripped/rejected rather than trusted, so this also prevents a
        # spoofed PROXY header from a non-edge peer forging client IPs.
        NB_PROXY_PROXY_PROTOCOL = "true";
        NB_PROXY_TRUSTED_PROXIES = "${node1PrivateIp}/32";
        # Explicit false (matches the binary's default): documents the
        # TLS strategy decision above in the running config, not just in
        # comments.
        NB_PROXY_ACME_CERTIFICATES = "false";
        # Wired unconditionally, unlike the edge module's
        # crowdsec.enable toggle: enforcement here is per-service, chosen
        # in the NetBird dashboard
        # (Reverse Proxy -> Services -> CrowdSec mode), not global, so
        # wiring the URL/key alone has no traffic impact by itself.
        # Verified fail-open against the v0.74.3 source
        # (proxy/internal/restrict/restrict.go `checkCrowdSec`): a service
        # left in `observe` (or unset) mode always resolves to Allow even
        # if the LAPI bouncer never connects; only a service explicitly
        # switched to `enforce` fails closed on an unreachable LAPI
        # (`DenyCrowdSecUnavailable`). Operators should start new services
        # in `observe` mode.
        NB_PROXY_CROWDSEC_API_URL = "http://${node1PrivateIp}:${toString lapiPort}";
        NB_PROXY_LOG_LEVEL = "info";
        # supports-custom-ports defaults to true upstream (preserves the
        # ability to freely add custom ports); nothing to set here. Custom
        # published-service ports are opened by the operator per service
        # (NetBird dashboard
        # + a matching `networking.firewall.allowedTCPPorts`/`allowedUDPPorts`
        # addition for legion-node2 when a service is actually published --
        # the inventory can't pre-declare ports it doesn't know about yet).
      };
      serviceConfig = {
        ExecStart = lib.getExe proxyPkg;
        EnvironmentFile = [config.sops.templates."netbird-proxy.env".path];
        Restart = "on-failure";
        RestartSec = 5;
        User = "netbird-proxy";
        Group = "netbird-proxy";
        # NB_PROXY_ADDRESS above binds :443; the proxy otherwise runs
        # unprivileged.
        AmbientCapabilities = ["CAP_NET_BIND_SERVICE"];
        MemoryMax = "128M";
      };
    };
  };
}
