# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub ({
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    });
    date = "2021-04-20";
  };
  wezterm = {
    pname = "wezterm";
    version = "cb5252a246a74958c4478495476ac99931a3a3d7";
    src = fetchFromGitHub ({
      owner = "wez";
      repo = "wezterm";
      rev = "cb5252a246a74958c4478495476ac99931a3a3d7";
      fetchSubmodules = true;
      sha256 = "sha256-MHyjLjkEC0AepKSTLWY4r2FpGm1hcKI3mQsefvas60A=";
    });
    date = "2023-03-27";
  };
}
