# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  joshuto = {
    pname = "joshuto";
    version = "1a7f79a66e5828cdb19910652677d03a12b66d6b";
    src = fetchFromGitHub ({
      owner = "kamiyaa";
      repo = "joshuto";
      rev = "1a7f79a66e5828cdb19910652677d03a12b66d6b";
      fetchSubmodules = false;
      sha256 = "sha256-u9jzPTu+HDyG+lKEIl09Ul5t8SLqEkpJ0Gb6KZx6Bgo=";
    });
    cargoLock."./Cargo.lock" = {
      lockFile = ./joshuto-1a7f79a66e5828cdb19910652677d03a12b66d6b/./Cargo.lock;
      outputHashes = { };
    };
    date = "2023-03-31";
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub ({
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    });
    date = "2021-04-20";
  };
  wezterm = {
    pname = "wezterm";
    version = "b2b5c64affb016adc3ed76c9361d7d129aaa6f62";
    src = fetchFromGitHub ({
      owner = "wez";
      repo = "wezterm";
      rev = "b2b5c64affb016adc3ed76c9361d7d129aaa6f62";
      fetchSubmodules = true;
      sha256 = "sha256-6AnLTE7PzBL3L8tFGxugaZJmZqIFwtniMEjYInkBO1o=";
    });
    cargoLock."./Cargo.lock" = {
      lockFile = ./wezterm-b2b5c64affb016adc3ed76c9361d7d129aaa6f62/./Cargo.lock;
      outputHashes = {
        "xcb-imdkit-0.2.0" = "sha256-QOT9HLlA26DVPUF4ViKH2ckexUsu45KZMdJwoUhW+hA=";
        "image-0.24.5" = "sha256-fTajVwm88OInqCPZerWcSAm1ga46ansQ3EzAmbT58Js=";
      };
    };
    date = "2023-04-04";
  };
}
