# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  joshuto = {
    pname = "joshuto";
    version = "cec35dbce007d37e5fb96b7d6997858d2914053b";
    src = fetchFromGitHub ({
      owner = "kamiyaa";
      repo = "joshuto";
      rev = "cec35dbce007d37e5fb96b7d6997858d2914053b";
      fetchSubmodules = false;
      sha256 = "sha256-0+eiVsOfqrXl0IBgJI9vU5SeGoTCKPTHquwILNiq72E=";
    });
    cargoLock."./Cargo.lock" = {
      lockFile = ./joshuto-cec35dbce007d37e5fb96b7d6997858d2914053b/./Cargo.lock;
      outputHashes = { };
    };
    date = "2023-04-10";
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub ({
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    });
    date = "2021-04-20";
  };
  wezterm = {
    pname = "wezterm";
    version = "9ec7973326338c2535fe8a3f53090f6011794fb4";
    src = fetchFromGitHub ({
      owner = "wez";
      repo = "wezterm";
      rev = "9ec7973326338c2535fe8a3f53090f6011794fb4";
      fetchSubmodules = true;
      sha256 = "sha256-6pvUKpvoJRW4LjCdAMt+fL7/1g6sih8v8lNd++jtMz4=";
    });
    cargoLock."./Cargo.lock" = {
      lockFile = ./wezterm-9ec7973326338c2535fe8a3f53090f6011794fb4/./Cargo.lock;
      outputHashes = {
        "xcb-imdkit-0.2.0" = "sha256-QOT9HLlA26DVPUF4ViKH2ckexUsu45KZMdJwoUhW+hA=";
        "image-0.24.5" = "sha256-fTajVwm88OInqCPZerWcSAm1ga46ansQ3EzAmbT58Js=";
      };
    };
    date = "2023-04-23";
  };
}
